os: linux
dist: focal
language: python

cache:
  pip: true

python:
  - '3.8'
  - '3.9'

install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt

before_script:
  - ln -s "$VIRTUAL_ENV" "$TRAVIS_BUILD_DIR/venv"
  - export FLASK_APP="$TRAVIS_BUILD_DIR/application.py"
  - export FLASK_DEBUG=1

script: make travis VER_PY="$TRAVIS_PYTHON_VERSION"
