dist: xenial
language: python

cache:
  pip: true
  directories:
    - "$TRAVIS_BUILD_DIR/venv"

python:
  - 3.5
  - 3.6
  - 3.7

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/application.py"
  - export FLASK_DEBUG=1

script: make travis VER_PY="$TRAVIS_PYTHON_VERSION"
