os: linux
dist: focal
language: python

cache:
  pip: true

python:
  - '3.9'
  - '3.10'
  - '3.11'

install:
  - >
    make \
      requirements-dev \
        VER_PY="$TRAVIS_PYTHON_VERSION" \
        DIR_VENV="$TRAVIS_BUILD_DIR/venv"

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/application.py"
  - export FLASK_DEBUG=1

script:
  - >
    make \
      travis \
        VER_PY="$TRAVIS_PYTHON_VERSION" \
        DIR_VENV="$TRAVIS_BUILD_DIR/venv"
